# EIT-P 云存储配置
# Cloud Storage Configuration for EIT-P Models

cloud_storage:
  # 支持的云存储提供商
  providers:
    - name: "aws_s3"
      enabled: true
      config:
        bucket: "eitp-models"
        region: "us-east-1"
        access_key: "${AWS_ACCESS_KEY_ID}"
        secret_key: "${AWS_SECRET_ACCESS_KEY}"
    
    - name: "google_cloud"
      enabled: true
      config:
        bucket: "eitp-models"
        project_id: "your-project-id"
        credentials_file: "path/to/credentials.json"
    
    - name: "azure_blob"
      enabled: true
      config:
        account_name: "eitpstorage"
        container_name: "models"
        connection_string: "${AZURE_STORAGE_CONNECTION_STRING}"
    
    - name: "aliyun_oss"
      enabled: true
      config:
        bucket: "eitp-models"
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        access_key_id: "${ALIYUN_ACCESS_KEY_ID}"
        access_key_secret: "${ALIYUN_ACCESS_KEY_SECRET}"

# 模型存储路径
model_storage:
  # 基础路径
  base_path: "models/"
  
  # 模型分类
  categories:
    - name: "checkpoints"
      path: "checkpoints/"
      description: "训练检查点"
    
    - name: "final_models"
      path: "final_models/"
      description: "最终训练模型"
    
    - name: "compressed_models"
      path: "compressed_models/"
      description: "压缩后模型"
    
    - name: "experiment_models"
      path: "experiments/"
      description: "实验模型"

# 下载配置
download:
  # 并发下载数
  max_concurrent: 5
  
  # 重试配置
  max_retries: 3
  retry_delay: 5
  
  # 缓存配置
  cache_dir: "./model_cache"
  cache_size_gb: 10

# 上传配置
upload:
  # 分片上传大小 (MB)
  chunk_size_mb: 100
  
  # 并发上传数
  max_concurrent: 3
  
  # 压缩配置
  compress: true
  compression_level: 6

# 模型元数据
metadata:
  # 必需字段
  required_fields:
    - "model_name"
    - "version"
    - "created_at"
    - "file_size"
    - "checksum"
  
  # 可选字段
  optional_fields:
    - "description"
    - "author"
    - "tags"
    - "performance_metrics"
    - "training_config"
    - "dependencies"
