version: '3.8'

services:
  eitp-training:
    build: .
    container_name: eitp-training
    runtime: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:32
      - CUDA_LAUNCH_BLOCKING=1
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    ports:
      - "8080:8080"  # 监控API
      - "8081:8081"  # 训练状态API
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "python3", "-c", "import eit_p; print('EIT-P is healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  eitp-monitor:
    build: .
    container_name: eitp-monitor
    command: python3 scripts/monitor_dashboard.py
    ports:
      - "8082:8082"  # 监控仪表板
    volumes:
      - ./logs:/app/logs
      - ./results:/app/results
    depends_on:
      - eitp-training
    restart: unless-stopped

  eitp-api:
    build: .
    container_name: eitp-api
    command: python3 scripts/api_server.py
    ports:
      - "8083:8083"  # REST API
    volumes:
      - ./results:/app/results
      - ./models:/app/models
    depends_on:
      - eitp-training
    restart: unless-stopped

networks:
  default:
    name: eitp-network
